USE [master]
GO
/****** Object:  Database [DB_TEST]    Script Date: 03/02/2024 05:05:59 p. m. ******/
CREATE DATABASE [DB_TEST]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_TEST', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_TEST.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_TEST_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_TEST_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DB_TEST] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_TEST].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_TEST] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_TEST] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_TEST] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_TEST] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_TEST] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_TEST] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_TEST] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_TEST] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_TEST] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_TEST] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_TEST] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_TEST] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_TEST] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_TEST] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_TEST] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_TEST] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_TEST] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_TEST] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_TEST] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_TEST] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_TEST] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_TEST] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_TEST] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_TEST] SET  MULTI_USER 
GO
ALTER DATABASE [DB_TEST] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_TEST] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_TEST] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_TEST] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_TEST] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_TEST] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_TEST', N'ON'
GO
ALTER DATABASE [DB_TEST] SET QUERY_STORE = ON
GO
ALTER DATABASE [DB_TEST] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DB_TEST]
GO
/****** Object:  Table [dbo].[CATEGORIES]    Script Date: 03/02/2024 05:05:59 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CATEGORIES](
	[CATEGORY_ID] [int] NOT NULL,
	[CATEGORY_NAME] [nvarchar](256) NULL,
	[DESCRIPTION] [nvarchar](1024) NULL,
	[PICTURE] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER_CUSTOMER_DEMO]    Script Date: 03/02/2024 05:05:59 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER_CUSTOMER_DEMO](
	[CUSTOMER_ID] [varchar](500) NULL,
	[CUSTOMER_TYPE_ID] [varchar](500) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER_DEMOGRAPHICS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER_DEMOGRAPHICS](
	[CUSTOMER_TYPE_ID] [varchar](500) NOT NULL,
	[CUSTOMER_DESC] [nvarchar](1024) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMERS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMERS](
	[CUSTOMER_ID] [varchar](500) NOT NULL,
	[COMPANY_NAME] [nvarchar](128) NULL,
	[CONTACT_NAME] [nvarchar](256) NULL,
	[CONTACT_TITLE] [nvarchar](128) NULL,
	[ADDRESS] [nvarchar](128) NULL,
	[CITY] [nvarchar](128) NULL,
	[REGION] [nvarchar](128) NULL,
	[POSTAL_CODE] [nvarchar](16) NULL,
	[COUNTRY] [nvarchar](128) NULL,
	[PHONE] [nvarchar](32) NULL,
	[FAX] [nvarchar](32) NULL,
PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE_TERRITORIES]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE_TERRITORIES](
	[EMPLOYEE_ID] [int] NULL,
	[TERRITORY_ID] [varchar](500) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEES]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEES](
	[EMPLOYEES_ID] [int] NOT NULL,
	[LAST_NAME] [nvarchar](128) NULL,
	[FIRST_NAME] [nvarchar](128) NULL,
	[TITLE] [nvarchar](128) NULL,
	[TIEL_OF_COURTESY] [nvarchar](128) NULL,
	[BIRDTH_DATE] [date] NULL,
	[HIRE_DATE] [date] NULL,
	[ADDRES] [nvarchar](128) NULL,
	[CITY] [nvarchar](128) NULL,
	[REGION] [nvarchar](128) NULL,
	[POSTAL_CODE] [nvarchar](16) NULL,
	[COUNTY] [nvarchar](128) NULL,
	[HOME_PHONE] [nvarchar](16) NULL,
	[EXTENSION] [nvarchar](16) NULL,
	[PHOTE] [varchar](500) NULL,
	[NOTE] [nvarchar](1056) NULL,
	[REPORTS_TO] [int] NULL,
	[PHOTE_PATH] [nvarchar](256) NULL,
PRIMARY KEY CLUSTERED 
(
	[EMPLOYEES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDER_DETAILS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER_DETAILS](
	[ORDER_ID] [int] NULL,
	[PRODUCT_ID] [int] NULL,
	[UNIT_PRICE] [money] NULL,
	[QUANTITY] [int] NULL,
	[DISCOUNT] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ORDERS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[ORDER_ID] [int] NOT NULL,
	[CUSTOMER_ID] [varchar](500) NULL,
	[EMPLOYEE_ID] [int] NULL,
	[ORDER_DATE] [date] NULL,
	[REQUIRED_DATE] [date] NULL,
	[SHIPPED_DATE] [date] NULL,
	[SHIP_VIA] [int] NULL,
	[FREIGHT] [int] NULL,
	[SHIP_NAME] [nvarchar](128) NULL,
	[SHIP_ADDRESS] [nvarchar](128) NULL,
	[SHIP_CITY] [nvarchar](128) NULL,
	[SHIP_REGION] [nvarchar](128) NULL,
	[SHIP_POSTAL_CODE] [nvarchar](16) NULL,
	[SHIP_COUNTRY] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS](
	[PRODUCT_ID] [int] NOT NULL,
	[PRODUCT_NAME] [nvarchar](128) NULL,
	[SUPPLIER_ID] [int] NULL,
	[CATEGORY_ID] [int] NULL,
	[QUANTITY_PER_UNIT] [varchar](64) NULL,
	[UNIT_PRICE] [money] NULL,
	[UNITS_IN_STOCK] [int] NULL,
	[UNITS_ON_ORDER] [int] NULL,
	[REORDER_LEVEL] [int] NULL,
	[DISCOUNTINUED] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REGION]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REGION](
	[REGION_ID] [int] NOT NULL,
	[REGION_DESCRIPTION] [nvarchar](1024) NULL,
PRIMARY KEY CLUSTERED 
(
	[REGION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SHIPPERS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SHIPPERS](
	[SHIPPER_ID] [int] NOT NULL,
	[COMPANY_DESCRIPTION] [nvarchar](1024) NULL,
	[PHONE] [nvarchar](16) NULL,
PRIMARY KEY CLUSTERED 
(
	[SHIPPER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SUPPLIERS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SUPPLIERS](
	[SUPPLIER_ID] [int] NOT NULL,
	[COMPAY_NAME] [nvarchar](128) NULL,
	[CONTACT_NAME] [nvarchar](128) NULL,
	[CONTACT_TITLE] [nvarchar](128) NULL,
	[ADDRES] [nvarchar](128) NULL,
	[CITY] [nvarchar](128) NULL,
	[REGION] [nvarchar](128) NULL,
	[POSTAL_CODE] [nvarchar](16) NULL,
	[COUNTY] [nvarchar](128) NULL,
	[PHONE] [nvarchar](32) NULL,
	[FAX] [nvarchar](32) NULL,
	[HOMEPAGE] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[SUPPLIER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TERRITORIES]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TERRITORIES](
	[TERRITORY_ID] [varchar](500) NOT NULL,
	[TERRITORY_DESCRIPCION] [nvarchar](1024) NULL,
	[REGION_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[TERRITORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[US_STATES]    Script Date: 03/02/2024 05:06:00 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[US_STATES](
	[STATE_ID] [int] NOT NULL,
	[STATE_NAME] [nvarchar](128) NULL,
	[STATE_ABBR] [nvarchar](128) NULL,
	[STATE_REGION] [nvarchar](128) NULL,
PRIMARY KEY CLUSTERED 
(
	[STATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IDX_EMPLOYEES]    Script Date: 03/02/2024 05:06:00 p. m. ******/
CREATE NONCLUSTERED INDEX [IDX_EMPLOYEES] ON [dbo].[EMPLOYEES]
(
	[EMPLOYEES_ID] ASC
)
INCLUDE([FIRST_NAME],[LAST_NAME]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDER_DETAILS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
CREATE NONCLUSTERED INDEX [IDX_ORDER_DETAILS] ON [dbo].[ORDER_DETAILS]
(
	[ORDER_ID] ASC,
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_PRODUCTO]    Script Date: 03/02/2024 05:06:00 p. m. ******/
CREATE NONCLUSTERED INDEX [IDX_PRODUCTO] ON [dbo].[ORDER_DETAILS]
(
	[PRODUCT_ID] ASC
)
INCLUDE([ORDER_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_ORDERS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
CREATE NONCLUSTERED INDEX [IDX_ORDERS] ON [dbo].[ORDERS]
(
	[ORDER_ID] ASC
)
INCLUDE([EMPLOYEE_ID],[ORDER_DATE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IDX_PRODUCTOS]    Script Date: 03/02/2024 05:06:00 p. m. ******/
CREATE NONCLUSTERED INDEX [IDX_PRODUCTOS] ON [dbo].[PRODUCTS]
(
	[PRODUCT_ID] ASC,
	[SUPPLIER_ID] ASC
)
INCLUDE([PRODUCT_NAME]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CUSTOMER_CUSTOMER_DEMO]  WITH CHECK ADD FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[CUSTOMERS] ([CUSTOMER_ID])
GO
ALTER TABLE [dbo].[CUSTOMER_CUSTOMER_DEMO]  WITH CHECK ADD FOREIGN KEY([CUSTOMER_TYPE_ID])
REFERENCES [dbo].[CUSTOMER_DEMOGRAPHICS] ([CUSTOMER_TYPE_ID])
GO
ALTER TABLE [dbo].[EMPLOYEE_TERRITORIES]  WITH CHECK ADD FOREIGN KEY([EMPLOYEE_ID])
REFERENCES [dbo].[EMPLOYEES] ([EMPLOYEES_ID])
GO
ALTER TABLE [dbo].[EMPLOYEE_TERRITORIES]  WITH CHECK ADD FOREIGN KEY([TERRITORY_ID])
REFERENCES [dbo].[TERRITORIES] ([TERRITORY_ID])
GO
ALTER TABLE [dbo].[ORDER_DETAILS]  WITH CHECK ADD FOREIGN KEY([ORDER_ID])
REFERENCES [dbo].[ORDERS] ([ORDER_ID])
GO
ALTER TABLE [dbo].[ORDER_DETAILS]  WITH CHECK ADD FOREIGN KEY([PRODUCT_ID])
REFERENCES [dbo].[PRODUCTS] ([PRODUCT_ID])
GO
USE [master]
GO
ALTER DATABASE [DB_TEST] SET  READ_WRITE 
GO
